# Generated by Django 4.2.13 on 2026-10-06 03:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(db_column='brgy_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='brgy_name', max_length=100, unique=True)),
                ('municipality', models.CharField(db_column='brgy_municipality', default='Talisay City', max_length=100)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, db_column='brgy_boundary', null=True, srid=4326)),
            ],
            options={
                'db_table': 'barangay',
            },
        ),
    ]
