# Generated by Django 4.2.13 on 2026-10-06 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hazards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(db_column='notf_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(db_column='notf_content')),
                ('is_read', models.BooleanField(db_column='notf_is_read', default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_column='notf_sent_at')),
                ('read_at', models.DateTimeField(blank=True, db_column='notf_read_at', null=True)),
                ('hazard_alert', models.ForeignKey(blank=True, db_column='notf_hzal_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hazards.hazardalert')),
                ('recipient', models.ForeignKey(db_column='notf_recipient_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-sent_at'],
            },
        ),
    ]
