# Generated by Django 4.2.13 on 2026-10-01 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hazards', '0002_hazardzone_verification_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(db_column='NOTF_ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(db_column='NOTF_CONTENT')),
                ('is_read', models.BooleanField(db_column='NOTF_IS_READ', default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_column='NOTF_SENT_AT')),
                ('read_at', models.DateTimeField(blank=True, db_column='NOTF_READ_AT', null=True)),
                ('hazard_alert', models.ForeignKey(blank=True, db_column='NOTF_HZAL_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hazards.hazardalert')),
                ('recipient', models.ForeignKey(db_column='NOTF_RECIPIENT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'NOTIFICATION',
                'ordering': ['-sent_at'],
            },
        ),
    ]
