import random
from pathlib import Path

from django.conf import settings
from django.contrib.gis.geos import MultiPolygon, Point, Polygon
from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
from django.utils import timezone
from faker import Faker

from apps.accounts.models import User
from apps.barangays.models import Barangay
from apps.hazards import fake_data
from apps.hazards.models import HazardType, HazardZone
from apps.history.models import HistoricalRecord


class Command(BaseCommand):
    help = (
        'Fill the map and the historical records with sample hazards generated by Faker. '
        'Events are placed on susceptible ground and dated by season, so the hazard-level '
        'layer and the historical trends look like Talisay City. Earlier samples are replaced; '
        'real hazards are never touched.'
    )

    def add_arguments(self, parser):
        parser.add_argument('--active', type=int, default=8,
                            help='Active hazards to put on the map (default 8).')
        parser.add_argument('--years', type=int, default=5,
                            help='Years of historical records to generate (default 5).')
        parser.add_argument('--seed', type=int, default=2026,
                            help='Random seed; the same seed gives the same data (default 2026).')
        parser.add_argument('--index', default=None,
                            help='Susceptibility folder (default: frontend/public/hazard-index).')
        parser.add_argument('--min-history', type=int, default=3,
                            help='Past records of the same hazard each active hazard\'s barangay gets at least (default 3).')
        parser.add_argument('--clear', action='store_true',
                            help='Only remove existing sample data, then stop.')

    def handle(self, *args, **options):
        if options['clear']:
            with transaction.atomic():
                self._clear()
            return

        types = {t.name: t for t in HazardType.objects.filter(name__in=fake_data.HAZARDS)}
        missing = set(fake_data.HAZARDS) - set(types)
        if missing:
            raise CommandError(f'Missing hazard types {sorted(missing)}. Run "python manage.py seed_data" first.')

        barangays = [(b, b.boundary.prepared) for b in Barangay.objects.exclude(boundary__isnull=True)]
        if not barangays:
            raise CommandError('No barangay boundaries in the database. Load the barangays first.')

        index_dir = Path(options['index']) if options['index'] else \
            Path(settings.BASE_DIR).parent / 'frontend' / 'public' / 'hazard-index'
        try:
            grids = fake_data.load_grids(index_dir)
        except FileNotFoundError as exc:
            raise CommandError(
                f'Susceptibility maps not found in {index_dir}. Run "python manage.py build_hazard_index" first.'
            ) from exc

        fake = Faker('fil_PH')
        fake.seed_instance(options['seed'])
        rnd = random.Random(options['seed'])
        spots = {h: fake_data.Spots(grids[h], rnd, fake_data.MIN_CLASS[h]) for h in fake_data.HAZARDS}
        now = timezone.now()

        history = fake_data.historical_events(spots, options['years'], now, fake, rnd)
        active = fake_data.active_events(spots, options['active'], now, fake, rnd)
        publisher = User.objects.filter(role__name='DRRMO_Officer', is_active=True).order_by('id').first()

        def barangay_at(lng, lat):
            point = Point(lng, lat, srid=4326)
            return next((b for b, prepared in barangays if prepared.contains(point)), None)

        added = self._top_up_history(history, active, barangay_at, grids, options, now, fake, rnd)

        def zone_for(event, status):
            ring = fake_data.circle_ring(event['lng'], event['lat'], event['radius_m'])
            barangay = barangay_at(event['lng'], event['lat'])
            return HazardZone(
                barangay=barangay,
                published_by=publisher,
                hazard_type=types[event['hazard']],
                severity=event['severity'],
                status=status,
                geometry=MultiPolygon(Polygon(ring), srid=4326),
                description=event['description'],
                resolved_at=event.get('resolved_at'),
                is_sample=True,
            )

        with transaction.atomic():
            self._clear()

            past = [zone_for(e, 'Resolved') for e in history]
            live = [zone_for(e, 'Active') for e in active]
            HazardZone.objects.bulk_create(past + live)

            # activated_at is auto_now_add, so the real dates go in afterwards
            for zone, e in zip(past + live, history + active):
                zone.activated_at = e['occurred_at']
            HazardZone.objects.bulk_update(past + live, ['activated_at'], batch_size=200)

            records = [
                HistoricalRecord(
                    barangay=zone.barangay,
                    hazard_type=zone.hazard_type,
                    hazard_zone=zone,
                    severity_level=zone.severity,
                    description=e['description'],
                    occurred_at=e['occurred_at'],
                    total_casualties=e['casualties'],
                    total_displaced=e['displaced'],
                    is_sample=True,
                )
                for zone, e in zip(past, history)
            ]
            HistoricalRecord.objects.bulk_create(records)
            for record, e in zip(records, history):
                record.archived_at = e['resolved_at']
            HistoricalRecord.objects.bulk_update(records, ['archived_at'], batch_size=200)

        by_type = {h: sum(e['hazard'] == h for e in history) for h in fake_data.HAZARDS}
        self.stdout.write(
            f'  ✓ {len(records)} historical records over {options["years"]} years '
            f'({", ".join(f"{n} {h.lower()}" for h, n in by_type.items())})'
        )
        self.stdout.write(f'  ✓ {len(live)} active hazards on the map')
        self.stdout.write(f'  ✓ {added} extra records so every active hazard\'s barangay has at least '
                          f'{options["min_history"]} past {"record" if options["min_history"] == 1 else "records"} of that hazard')
        self.stdout.write(self.style.SUCCESS('Sample hazards ready. Remove them with --clear.'))

    def _top_up_history(self, history, active, barangay_at, grids, options, now, fake, rnd):
        """
        Make sure each active hazard (sample or real) has at least --min-history
        past records of the same type in its barangay, so its History tab and
        the heat shading around it aren't empty. Returns how many were added.
        """
        need = options['min_history']
        if need <= 0:
            return 0

        # Records already there: real ones in the database plus the samples generated above
        counts = {}
        real = HistoricalRecord.objects.filter(is_sample=False).values_list('hazard_type__name', 'barangay_id')
        for hazard, barangay_id in real:
            counts[(hazard, barangay_id)] = counts.get((hazard, barangay_id), 0) + 1
        for e in history:
            b = barangay_at(e['lng'], e['lat'])
            key = (e['hazard'], b.id if b else None)
            counts[key] = counts.get(key, 0) + 1

        # Where hazards are active: the sample ones about to be created and the real ones
        targets = [(e['hazard'], e['lng'], e['lat']) for e in active]
        for zone in HazardZone.objects.filter(status='Active', is_sample=False).select_related('hazard_type'):
            if zone.hazard_type and zone.hazard_type.name in fake_data.HAZARDS and zone.geometry:
                p = zone.geometry.point_on_surface
                targets.append((zone.hazard_type.name, p.x, p.y))

        added = 0
        for hazard, lng, lat in targets:
            home = barangay_at(lng, lat)
            if home is None:
                continue  # outside every barangay: there is no area history to show
            key = (hazard, home.id)
            attempts = 0
            while counts.get(key, 0) < need and attempts < 40:
                attempts += 1
                event = fake_data.past_event_near(hazard, lng, lat, grids[hazard], options['years'], now, fake, rnd)
                landed = barangay_at(event['lng'], event['lat'])
                if landed is None or landed.id != home.id:
                    continue  # drifted over the boundary; try another spot
                history.append(event)
                counts[key] = counts.get(key, 0) + 1
                added += 1
        history.sort(key=lambda e: e['occurred_at'])
        return added

    def _clear(self):
        records, _ = HistoricalRecord.objects.filter(is_sample=True).delete()
        zones = HazardZone.objects.filter(is_sample=True)
        zone_count = zones.count()
        zones.delete()  # their alerts and notifications go with them
        self.stdout.write(f'  Removed {zone_count} sample zones and {records} sample records')
