# Generated by Django 4.2.13 on 2026-10-06 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(db_column='audl_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_column='audl_action', max_length=100)),
                ('target_table', models.CharField(blank=True, db_column='audl_target_table', max_length=100)),
                ('target_id', models.CharField(blank=True, db_column='audl_target_id', max_length=100)),
                ('details', models.TextField(blank=True, db_column='audl_detail')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_column='audl_ip_address', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='audl_created_at')),
                ('user', models.ForeignKey(blank=True, db_column='audl_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
