# Generated by Django 5.2.17 on 2026-09-12 05:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barangays', '0001_initial'),
        ('hazards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity_level', models.CharField(choices=[('Red', 'Extreme'), ('Orange', 'Moderate'), ('Green', 'Low')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('total_casualties', models.IntegerField(blank=True, null=True)),
                ('total_displaced', models.IntegerField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='barangays.barangay')),
                ('hazard_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hazards.hazardtype')),
                ('hazard_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hazards.hazardzone')),
            ],
            options={
                'db_table': 'historical_record',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
