# Generated by Django 4.2.13 on 2026-10-06 03:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barangays', '0001_initial'),
        ('hazards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRecord',
            fields=[
                ('id', models.UUIDField(db_column='hstr_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity_level', models.CharField(choices=[('Red', 'Extreme'), ('Orange', 'Moderate'), ('Green', 'Low')], db_column='hstr_severity', max_length=20)),
                ('description', models.TextField(blank=True, db_column='hstr_desc')),
                ('occurred_at', models.DateTimeField(db_column='hstr_occurred_at')),
                ('total_casualties', models.IntegerField(blank=True, db_column='hstr_total_casualties', null=True)),
                ('total_displaced', models.IntegerField(blank=True, db_column='hstr_total_displaced', null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True, db_column='hstr_archived_at')),
                ('barangay', models.ForeignKey(db_column='hstr_brgy_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='barangays.barangay')),
                ('hazard_type', models.ForeignKey(db_column='hstr_hztp_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hazards.hazardtype')),
                ('hazard_zone', models.ForeignKey(blank=True, db_column='hstr_hzzn_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hazards.hazardzone')),
            ],
            options={
                'db_table': 'historical_record',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
