# Generated by Django 4.2.13 on 2026-10-06 03:16

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barangays', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardType',
            fields=[
                ('id', models.BigAutoField(db_column='hztp_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='hztp_name', max_length=50, unique=True)),
                ('logo_class', models.CharField(blank=True, db_column='hztp_icon_class', max_length=50)),
                ('is_active', models.BooleanField(db_column='hztp_is_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='hztp_created_at')),
            ],
            options={
                'db_table': 'hazard_type',
            },
        ),
        migrations.CreateModel(
            name='HazardZone',
            fields=[
                ('id', models.UUIDField(db_column='hzzn_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('Red', 'Extreme'), ('Orange', 'Moderate'), ('Green', 'Low')], db_column='hzzn_severity', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Resolved', 'Resolved'), ('Archived', 'Archived')], db_column='hzzn_status', default='Active', max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(db_column='hzzn_polygon', srid=4326)),
                ('description', models.TextField(blank=True, db_column='hzzn_desc')),
                ('activated_at', models.DateTimeField(auto_now_add=True, db_column='hzzn_activated_at')),
                ('resolved_at', models.DateTimeField(blank=True, db_column='hzzn_resolved_at', null=True)),
                ('verification_status', models.CharField(choices=[('Pending', 'Awaiting barangay confirmation'), ('Confirmed', 'Confirmed by barangay'), ('Disputed', 'Disputed by barangay')], db_column='hzzn_verification_status', default='Pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, db_column='hzzn_verified_at', null=True)),
                ('verification_note', models.TextField(blank=True, db_column='hzzn_verification_note', default='')),
                ('barangay', models.ForeignKey(db_column='hzzn_brgy_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='barangays.barangay')),
                ('hazard_type', models.ForeignKey(db_column='hzzn_hztp_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hazards.hazardtype')),
                ('published_by', models.ForeignKey(db_column='hzzn_published_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, db_column='hzzn_verified_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_hazard_zones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hazard_zone',
            },
        ),
        migrations.CreateModel(
            name='HazardAlert',
            fields=[
                ('id', models.UUIDField(db_column='hzal_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(db_column='hzal_severity', max_length=20)),
                ('notes', models.TextField(blank=True, db_column='hzal_notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='hzal_created_at')),
                ('hazard_type', models.ForeignKey(db_column='hzal_hztp_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hazards.hazardtype')),
                ('hazard_zone', models.ForeignKey(db_column='hzal_hzzn_id', on_delete=django.db.models.deletion.CASCADE, to='hazards.hazardzone')),
                ('issued_by', models.ForeignKey(db_column='hzal_published_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hazard_alert',
            },
        ),
    ]
