# Generated by Django 4.2.13 on 2026-10-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardzone',
            name='is_sample',
            field=models.BooleanField(db_column='hzzn_is_sample', default=False),
        ),
    ]
