# Generated by Django 4.2.13 on 2026-09-27 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hazards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardzone',
            name='verification_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hazardzone',
            name='verification_status',
            field=models.CharField(choices=[('Pending', 'Awaiting barangay confirmation'), ('Confirmed', 'Confirmed by barangay'), ('Disputed', 'Disputed by barangay')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='hazardzone',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hazardzone',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_hazard_zones', 
            to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE hazard_zone ALTER COLUMN verification_status SET DEFAULT 'Pending';
                ALTER TABLE hazard_zone ALTER COLUMN verification_note SET DEFAULT '';
            """,
            reverse_sql="""
                ALTER TABLE hazard_zone ALTER COLUMN verification_status DROP DEFAULT;
                ALTER TABLE hazard_zone ALTER COLUMN verification_note DROP DEFAULT;
            """,
        ),
    ]
