# Generated by Django 4.2.13 on 2026-10-06 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hazards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidanceContent',
            fields=[
                ('id', models.UUIDField(db_column='gdcn_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='gdcn_title', max_length=200)),
                ('body', models.TextField(db_column='gdcn_body')),
                ('timeline_phase', models.CharField(choices=[('Before', 'Before'), ('During', 'During'), ('After', 'After')], db_column='gdcn_phase', max_length=10)),
                ('is_published', models.BooleanField(db_column='gdcn_is_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='gdcn_created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='gdcn_updated_at')),
                ('created_by', models.ForeignKey(db_column='gdcn_created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hazard_type', models.ForeignKey(db_column='gdcn_hztp_id', on_delete=django.db.models.deletion.CASCADE, to='hazards.hazardtype')),
            ],
            options={
                'db_table': 'guidance_content',
                'ordering': ['hazard_type', 'timeline_phase'],
            },
        ),
    ]
