# Generated by Django 4.2.13 on 2026-10-06 03:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(db_column='role_id', primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('System_Admin', 'System Administrator'), ('DRRMO_Officer', 'DRRMO Officer'), ('Barangay_Personnel', 'Barangay Personnel')], db_column='role_name', max_length=40, unique=True)),
                ('description', models.TextField(blank=True, db_column='role_desc')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(db_column='user_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_column='user_full_name', max_length=150)),
                ('email', models.EmailField(db_column='user_email', max_length=254, unique=True)),
                ('failed_login_count', models.IntegerField(db_column='user_failed_login_count', default=0)),
                ('locked_until', models.DateTimeField(blank=True, db_column='user_locked_until', null=True)),
                ('is_active', models.BooleanField(db_column='user_is_active', default=True)),
                ('is_staff', models.BooleanField(db_column='user_is_staff', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='user_created_at')),
                ('password', models.CharField(db_column='user_password_hash', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, db_column='user_last_login', null=True)),
                ('is_superuser', models.BooleanField(db_column='user_is_superuser', default=False)),
                ('two_factor_enabled', models.BooleanField(db_column='user_two_factor_enabled', default=False)),
                ('two_factor_secret', models.CharField(blank=True, db_column='user_two_factor_secret', max_length=32, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('role', models.ForeignKey(blank=True, db_column='user_role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'app_user',
            },
        ),
    ]
