# Generated by Django 4.2.13 on 2026-10-06 03:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barangays', '0001_initial'),
        ('hazards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.UUIDField(db_column='incr_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(db_column='incr_desc')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Validated', 'Validated'), ('Rejected', 'Rejected')], db_column='incr_status', default='Pending', max_length=20)),
                ('review_note', models.TextField(blank=True, db_column='incr_review_note')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='incr_created_at')),
                ('reviewed_at', models.DateTimeField(blank=True, db_column='incr_reviewed_at', null=True)),
                ('reporter_name', models.CharField(blank=True, db_column='incr_reporter_name', default='', max_length=150)),
                ('agency', models.CharField(blank=True, db_column='incr_agency', default='', max_length=150)),
                ('position', models.CharField(blank=True, db_column='incr_position', default='', max_length=100)),
                ('severity_estimate', models.CharField(blank=True, db_column='incr_severity_estimate', default='', max_length=20)),
                ('submitted_at', models.DateTimeField(db_column='incr_submitted_at', default=django.utils.timezone.now)),
                ('validated_at', models.DateTimeField(blank=True, db_column='incr_validated_at', null=True)),
                ('casualties_dead', models.IntegerField(blank=True, db_column='incr_casualties_dead', default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('casualties_injured', models.IntegerField(blank=True, db_column='incr_casualties_injured', default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('casualties_missing', models.IntegerField(blank=True, db_column='incr_casualties_missing', default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('displaced', models.IntegerField(blank=True, db_column='incr_displaced', default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('barangay', models.ForeignKey(db_column='incr_brgy_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='barangays.barangay')),
                ('hazard_type', models.ForeignKey(db_column='incr_hztp_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hazards.hazardtype')),
                ('hazard_zone', models.ForeignKey(blank=True, db_column='incr_hzzn_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hazards.hazardzone')),
                ('historical_record', models.ForeignKey(blank=True, db_column='incr_hstr_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.historicalrecord')),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='incr_reviewed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(db_column='incr_submitted_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, db_column='incr_validated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incident_report',
                'ordering': ['-created_at'],
            },
        ),
    ]
